branch-defaults:
  main:
    environment: major-project-env
    group_suffix: null
environment-defaults:
  major-project-env:
    branch: null
    repository: null
global:
  application_name: major-project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
